services:
  healthcheck:
    image: alpine:3.22.1
    container_name: healthcheck
    restart: always
    network_mode: host
    env_file:
      - ../.env/.env.default
      - ../.env/.env.healthcheck
    command: >
      sh -c "
      apk add --no-cache curl &&
      while true; do
        echo \"\$(date '+%Y-%m-%d %H:%M:%S'): \$(curl -s -o /dev/null -w '%{http_code}' $${URL})\";
        sleep 59;
      done"