services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor
    restart: always
    privileged: true
    command:
      - -docker_only=true
      - -housekeeping_interval=15s
      - -disable_metrics=cpu_topology,disk,memory_numa,tcp,udp,percpu,sched,hugetlb,referenced_memory,resctrl,cpuset,advtcp,diskIO
    networks:
      - monitor
    volumes:
      - /:/rootfs:ro
      - /run:/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
networks:
  monitor:
    external: true