services:
  grafana:
    image: grafana/grafana:11.6.4
    container_name: grafana
    restart: always
    networks:
      - monitor
      - internal_ui
    volumes:
      - grafana:/var/lib/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.service=grafana"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=myresolver"
      - "traefik.http.routers.grafana.rule=Host(`grafana.panda.tsphotoclicks.net`)"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    env_file:
      - ../.env/.env.default
      - ../.env/monitor/.env.grafana
volumes:
  grafana:
    external: true
networks:
  internal_ui:
    external: true
  monitor:
    external: true
