services:
  nodeexporter:
    image: prom/node-exporter:v1.8.2
    container_name: nodeexporter
    restart: always
    network_mode: host
    ports:
      - "127.0.0.1:9100:9100"
    command:
      - '--path.rootfs=/host'
    pid: host
    volumes:
      - '/:/host:ro,rslave'