services:
  nodeexporter:
    image: prom/node-exporter:v1.9.0
    container_name: nodeexporter
    restart: always
    networks:
      - monitor
    command:
      - '--path.rootfs=/host'
    pid: host
    volumes:
      - '/:/host:ro'