services:
  unifipoller:
    image: ghcr.io/unpoller/unpoller:v2.14.0
    container_name: unifipoller
    restart: always
    networks:
      - monitor
    env_file:
      - ../.env/monitor/.env.unifipoller
networks:
  monitor:
    external: true
  