services:
  portaineragent:
    image: portainer/agent:2.38.1
    container_name: portaineragent
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /volume1/docker:/var/lib/docker/volumes
      - /:/host:ro
    ports:
      - 9001:9001
