services:
  cloudflaretunnel:
    image: cloudflare/cloudflared:2024.12.1
    container_name: cloudflaretunnel
    restart: always
    networks:
      - backend
    command: tunnel --no-autoupdate run
    env_file:
      - ../.env/.env.default
      - ../.env/network/.env.cloudflaretunnel
networks:
  backend:
    external: true
