services:
  macbookpro:
    image: "portainer/agent:2.28.0-alpine"
    container_name: "macbookpro"
    restart: always
    networks:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host
    ports:
      - "9001:9001"
    env_file:
      - ../.env/.env.default
      - ../.env/network/.env.macbookpro
volumes:
  mackbookpro_data:
    external: true
networks:
  backend:
    external: true