services:
  macbookpro:
    image: "portainer/agent:2.21.2"
    container_name: "macbookpro"
    restart: always
    networks:
      - traefik_internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host
    ports:
      - "9001:9001"

volumes:
  mackbookpro_data:
    external: true
