services:
  macbookpro:
    image: "portainer/agent:2.22.0-alpine"
    container_name: "macbookpro"
    restart: always
    networks:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host
    ports:
      - "9001:9001"
    environment:
      - "AGENT_SECRET=${AGENT_SECRET}"
volumes:
  mackbookpro_data:
    external: true
networks:
  backend:
    external: true