services:
  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: prometheus
    restart: always
    networks:
      - backend
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    volumes:
      - prometheus_data:/prometheus
      - ../config/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
    ports:
      - 9090:9090
    env_file:
      - ../.env/.env.default
  grafana:
    image: grafana/grafana:11.2.2
    container_name: grafana
    restart: always
    networks:
      - traefik_internal
      - backend
    volumes:
      - grafana_data:/var/lib/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.service=grafana"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=myresolver"
      - "traefik.http.routers.grafana.rule=Host(`grafana.panda.tsphotoclicks.net`)"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    env_file:
      - ../.env/.env.default
volumes:
  prometheus_data:
    external: true
  grafana_data:
    external: true
