services:
  portainer:
    image: "portainer/portainer-ee:2.25.0"
    container_name: "portainer"
    restart: always
    networks:
      - internal_ui
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.service=portainer"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls.certresolver=myresolver"
      - "traefik.http.routers.portainer.rule=Host(`portainer.panda.tsphotoclicks.net`)"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    ports:
      - "8000:8000"
      # - "9000:9000"
volumes:
  portainer_data:
    external: true
networks:
  internal_ui:
    external: true
