services:
  traefik:
    image: "portainer/portainer-ee:2.21.1"
    container_name: "portainer"
    restart: always
    networks:
      - traefik_internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.service=portainer"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls.certresolver=myresolver"
      - "traefik.http.routers.portainer.rule=Host(`portainer.panda.tsphotoclicks.net`)"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    ports:
      - "8000:8000"

volumes:
  portainer_data:
    external: true

networks:
  traefik_internal:
    external: true

# Test 1