services:
  terraform:
    image: hashicorp/tfc-agent:1.20.2
    container_name: terraform
    restart: always
    env_file:
      - ../.env/.env.default
      - ../.env/network/.env.terraform
    networks:
      - backend
networks:
  backend:
    external: true