services:
  traefik:
    image: "traefik:v3.1.6"
    container_name: "traefik"
    restart: always
    networks:
      - internal_ui
    volumes:
      - traefik_certs:/ssl-certs
      - /var/run/docker.sock:/var/run/docker.sock:ro

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-dashboard.tls=true"
      - "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
      - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.panda.tsphotoclicks.net`)"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"
      - "traefik.http.routers.traefik-dashboard.tls.domains[0].main=panda.tsphotoclicks.net"
      - "traefik.http.routers.traefik-dashboard.tls.domains[0].sans=*.panda.tsphotoclicks.net"
      - "traefik.http.routers.traefik-dashboard.tls.certresolver=myresolver"
      - "traefik.http.services.noop.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.authentik.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.authentik.forwardauth.address=http://authentik_server:9000/outpost.goauthentik.io/auth/traefik"
      - "traefik.http.middlewares.authentik.forwardauth.authResponseHeaders=X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid,X-authentik-jwt,X-authentik-meta-jwks,X-authentik-meta-outpost,X-authentik-meta-provider,X-authentik-meta-app,X-authentik-meta-version,authorization"
      
    command:
      - "--global.checknewversion=true"
      - "--global.sendanonymoususage=false"
      # - "--log.level=DEBUG"
      - "--api.insecure=true"
      # - "--api.dashboard=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls.certresolver=myresolver"
      - "--entrypoints.websecure.http.tls.domains[0].main=panda.tsphotoclicks.net"
      - "--entrypoints.websecure.http.tls.domains[0].sans=*.panda.tsphotoclicks.net"

      - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.myresolver.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=admin@tsphotoclicks.com"
      - "--certificatesresolvers.myresolver.acme.storage=/ssl-certs/acme.json"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53"

      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=internal_ui"

      - "--serversTransport.insecureSkipVerify=true"

    ports:
      - "80:80"
      - "443:443"

    env_file:
      - ../.env/.env.default
      - ../.env/.env.traefik

volumes:
  traefik_certs:
    external: true

networks:
  internal_ui:
    external: true
