version: '3.1'
services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate --credentials-file /run/secrets/cloudflare_token run 32127610-0f1a-4e5b-8125-0cb056d5fdbf
    restart: always
    secrets:
      - cloudflare_token

secrets:
  cloudflare_token:
    external: true
