services:
  vscode:
    image: linuxserver/code-server:4.103.1
    container_name: vscode
    hostname: vscode
    restart: always
    networks:
      - internal_ui
    volumes:
      - code_server:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vscode.service=vscode"
      - "traefik.http.routers.vscode.entrypoints=websecure"
      - "traefik.http.routers.vscode.tls=true"
      - "traefik.http.routers.vscode.rule=Host(`vscode.beast.tsphotoclicks.net`)"
      - "traefik.http.services.vscode.loadbalancer.server.port=8443"
      - "traefik.http.routers.vscode.middlewares=authentik@docker"
    env_file:
      - ../.env/.env.default
      - ../.env/utility/.env.vscode
volumes:
  code_server:
    external: true

networks:
  internal_ui:
    external: true
