services:
  qbittorrent:
    image: linuxserver/qbittorrent:5.1.4
    container_name: qbittorrent
    restart: always
    network_mode: "service:gluetun"
    volumes:
      - qbittorrent:/config
      - /ssd_cache/downloads:/downloads
    depends_on:
      - gluetun
    env_file:
      - ../.env/.env.default
      - ../.env/media/.env.qbittorrent
volumes:
  qbittorrent:
    external: true
  downloads:
    external: true