services:
  radarr:
    image: linuxserver/radarr:5.28.0
    container_name: radarr
    restart: always
    network_mode: "service:gluetun"
    volumes:
      - radarr:/config
      - /ssd_video/movies:/movies
      - /ssd_cache/downloads:/downloads
    depends_on:
      - gluetun
    env_file:
      - ../.env/.env.default
volumes:
  radarr:
    external: true
  downloads:
    external: true