services:
  sonarr:
    image: linuxserver/sonarr:4.0.16
    container_name: sonarr
    restart: always
    network_mode: "service:gluetun"
    volumes:
      - sonarr:/config
      - /ssd_video/tvshows:/tv
      - /ssd_cache/downloads:/downloads
    depends_on:
      - gluetun
    env_file:
      - ../.env/.env.default
volumes:
  sonarr:
    external: true
  downloads:
    external: true