services:
  tdarr:
    image: ghcr.io/haveagitgat/tdarr:latest
    container_name: tdarr
    restart: always
    networks:
      - internal_ui
    volumes:
      - tdarr:/app/server
      - tdarr_config:/app/configs
      - tdarr_log:/app/logs
      - /ssd_video:/Volumes/video
      - /ssd_cache/tdarr:/Volumes/cache/tdarr
    ports:
      - 8266:8266
    env_file:
      - ../.env/.env.default
      - ../.env/media/.env.tdarr
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tdarr.service=tdarr"
      - "traefik.http.routers.tdarr.entrypoints=websecure"
      - "traefik.http.routers.tdarr.tls.certresolver=myresolver"
      - "traefik.http.routers.tdarr.rule=Host(`tdarr.beast.tsphotoclicks.net`)"
      - "traefik.http.services.tdarr.loadbalancer.server.port=8265"
      - "traefik.http.routers.tdarr.middlewares=authentik@docker"
    devices:
      - /dev/dri:/dev/dri
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]

volumes:
  tdarr:
    external: true
  tdarr_config:
    external: true
  tdarr_log:
    external: true

networks:
  internal_ui:
    external: true