services:
  nodeexporter:
    image: prom/node-exporter:v1.9.1
    container_name: nodeexporter
    restart: always
    networks:
      - monitor
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.ignored-mount-points"
      - "^/(rootfs/)?(dev|etc|host|proc|run|sys|volume1)($$|/)"
    pid: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    ports:
      - 10100:9100
networks:
  monitor:
    external: true