services: 
  diun: 
    image: crazymax/diun:4.29.0
    container_name: diun
    hostname: panda
    restart: always
    command: serve
    networks:
      - apps
    volumes:
      - diun_data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file:
      - ../.env/.env.default
      - ../.env/apps/.env.diun
volumes:
  diun_data:
    external: true
networks:
  apps:
    external: true
