services:
  dozzle:
    image: amir20/dozzle:v8.6.0
    container_name: dozzle
    restart: always
    networks:
      - traefik_internal
    volumes:
      - dozzle:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dozzle.service=dozzle"
      - "traefik.http.routers.dozzle.entrypoints=websecure"
      - "traefik.http.routers.dozzle.tls.certresolver=myresolver"
      - "traefik.http.routers.dozzle.rule=Host(`dozzle.panda.tsphotoclicks.net`)"
      - "traefik.http.services.dozzle.loadbalancer.server.port=8080"
    env_file:
      - ../.env/.env.default
volumes:
  dozzle:
    external: true
networks:
  traefik_internal:
    external: true
