services:
  immich_db:
    image: tensorchord/pgvecto-rs:pg16-v0.2.0
    container_name: immich_db
    restart: always
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 30s
      interval: 10s
      retries: 5
      timeout: 10s
    env_file:
      - ../.env/.env.immich_db
    volumes:
      - /home/master/bin/immich_db:/var/lib/postgresql/data
  immich_redis:
    image: redis:7.4.0-alpine
    container_name: immich_redis
    restart: always
    healthcheck:
      test: redis-cli ping || exit 1
  immich_server:
    image: ghcr.io/immich-app/immich-server:v1.117.0
    container_name: immich_server
    restart: always
    healthcheck:
      disable: false
    devices:
      - /dev/dri:/dev/dri
    env_file:
      - ../.env/.env.immich
    volumes:
      - /home/master/bin/immich:/usr/src/app/upload
      - /media/master/Extreme\ Pro/photo/DSLR:/mnt/dslr:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.immich.service=immich"
      - "traefik.http.routers.immich.entrypoints=websecure"
      - "traefik.http.routers.immich.tls.certresolver=myresolver"
      - "traefik.http.routers.immich.rule=Host(`immich.panda.tsphotoclicks.net`)"
      - "traefik.http.services.immich.loadbalancer.server.port=3001"
    depends_on:
      - immich_db
      - immich_redis
  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:v1.117.0-openvino
    container_name: immich_ml
    restart: always
    healthcheck:
      disable: false
    device_cgroup_rules:
      - 'c 189:* rmw'
    devices:
      - /dev/dri:/dev/dri
    env_file:
      - ../.env/.env.immich
    volumes:
      - immich_ml:/cache
      - /dev/bus/usb:/dev/bus/usb
volumes:
  immich_ml:
    external: true
networks:
  traefik_internal:
    external: true