services:
  sonarr:
    image: linuxserver/sonarr:4.0.9
    container_name: sonarr
    restart: always
    networks:
      - traefik_internal
    volumes:
      - sonarr:/config
      - /TVShow:/tv
      - /Downloads:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.service=sonarr"
      - "traefik.http.routers.sonarr.entrypoints=websecure"
      - "traefik.http.routers.sonarr.tls.certresolver=myresolver"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.panda.tsphotoclicks.net`)"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
    environment:
      - "TZ=America/Phoenix"
volumes:
  sonarr:
    external: true

networks:
  traefik_internal:
    external: true
