services:
  tfc-agent:
    image: hashicorp/tfc-agent:latest
    secrets:
      - agent_token
    entrypoint: sh -c 'export TFC_AGENT_TOKEN=$(cat /run/secrets/agent_token) && /home/tfc-agent/bin/tfc-agent'

secrets:
  agent_token:
    file: /home/master/bin/secrets/terraform_agent_token