global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  # external_labels:
  #  monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  # Job for Unifi Poller
  - job_name: 'unifipoller'
    scrape_interval: 5s
    static_configs:
      - targets:
        - https://unifi.tsphotoclicks.net
    metrics_path: /scrape
    relabel_configs:
     - source_labels: [__address__]
       target_label: __param_target
     - source_labels: [__param_target]
       target_label: instance
     - target_label: __address__
       replacement: unifipoller:9130

  # Job for node_exporter Panda Hostname
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['nodeexporter:9100']
        labels:
          instance: 'panda'

  # Job for cadvisor Panda Hostname
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          instance: 'panda'