services:
  bazarr:
    image: linuxserver/bazarr:1.5.4
    container_name: bazarr
    restart: always
    network_mode: "service:gluetun"
    volumes:
      - bazarr:/config
      - downloads:/downloads
      - /Movie:/movies
      - /TVShow:/tv
    depends_on:
      - gluetun
    env_file:
      - ../.env/.env.default
volumes:
  bazarr:
    external: true
  downloads:
    external: true