services:
  bazarr:
    image: linuxserver/bazarr:1.4.4
    container_name: bazarr
    restart: always
    network_mode: "service:gluetun"
    volumes:
      - bazarr:/config
      - downloads:/downloads
      - /Movie:/movies
      - /TVShow:/tv
    depends_on:
      - gluetun
    environment:
      - "TZ=America/Phoenix"
volumes:
  bazarr:
    external: true
  downloads:
    external: true