services: 
  emby: 
    image: emby/embyserver:4.9.1.32
    container_name: emby
    restart: always
    networks:
      - internal_ui
    volumes:
      - emby:/config
      - /TVShow:/tvshow
      - /Movie:/movie
    env_file:
      - ../.env/.env.default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.emby.service=emby"
      - "traefik.http.routers.emby.entrypoints=websecure"
      - "traefik.http.routers.emby.tls.certresolver=myresolver"
      - "traefik.http.routers.emby.rule=Host(`emby.panda.tsphotoclicks.net`)"
      - "traefik.http.services.emby.loadbalancer.server.port=8096"
volumes:
  emby:
    external: true

networks:
  internal_ui:
    external: true
