services:
  flaresolverr:
    image: flaresolverr/flaresolverr:v3.3.21
    container_name: flaresolverr
    restart: always
    network_mode: "service:gluetun"
    volumes:
      - flaresolverr:/config
    depends_on:
      - gluetun
    environment:
      - "TZ=America/Phoenix"
      - "LOG_LEVEL=info"
volumes:
  flaresolverr:
    external: true
