services:
  gluetun:
    image: qmcgaw/gluetun:v3.40.3
    container_name: gluetun
    restart: always
    networks:
      - internal_ui
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - gluetun:/gluetun
    labels:
      - "traefik.enable=true"
      # Bazarr related labels
      - "traefik.http.routers.vpn-bazarr.service=vpn-bazarr"
      - "traefik.http.routers.vpn-bazarr.entrypoints=websecure"
      - "traefik.http.routers.vpn-bazarr.tls.certresolver=myresolver"
      - "traefik.http.routers.vpn-bazarr.rule=Host(`bazarr.panda.tsphotoclicks.net`)"
      - "traefik.http.services.vpn-bazarr.loadbalancer.server.port=6767"
      - "traefik.http.routers.vpn-bazarr.middlewares=authentik@docker"
      # Prowlarr related labels
      - "traefik.http.routers.vpn-prowlarr.service=vpn-prowlarr"
      - "traefik.http.routers.vpn-prowlarr.entrypoints=websecure"
      - "traefik.http.routers.vpn-prowlarr.tls.certresolver=myresolver"
      - "traefik.http.routers.vpn-prowlarr.rule=Host(`prowlarr.panda.tsphotoclicks.net`)"
      - "traefik.http.services.vpn-prowlarr.loadbalancer.server.port=9696"
      - "traefik.http.routers.vpn-prowlarr.middlewares=authentik@docker"
      # Qbittorrent related labels
      - "traefik.http.routers.vpn-qbittorrent.service=vpn-qbittorrent"
      - "traefik.http.routers.vpn-qbittorrent.entrypoints=websecure"
      - "traefik.http.routers.vpn-qbittorrent.tls.certresolver=myresolver"
      - "traefik.http.routers.vpn-qbittorrent.rule=Host(`qbittorrent.panda.tsphotoclicks.net`)"
      - "traefik.http.services.vpn-qbittorrent.loadbalancer.server.port=8085"
      - "traefik.http.routers.vpn-qbittorrent.middlewares=authentik@docker"
      # SABnzbd related labels
      - "traefik.http.routers.vpn-sabnzbd.service=vpn-sabnzbd"
      - "traefik.http.routers.vpn-sabnzbd.entrypoints=websecure"
      - "traefik.http.routers.vpn-sabnzbd.tls.certresolver=myresolver"
      - "traefik.http.routers.vpn-sabnzbd.rule=Host(`sabnzbd.panda.tsphotoclicks.net`)"
      - "traefik.http.services.vpn-sabnzbd.loadbalancer.server.port=8080"
      - "traefik.http.routers.vpn-sabnzbd.middlewares=authentik@docker"  
      # Radarr related labels
      - "traefik.http.routers.vpn-radarr.service=vpn-radarr"
      - "traefik.http.routers.vpn-radarr.entrypoints=websecure"
      - "traefik.http.routers.vpn-radarr.tls.certresolver=myresolver"
      - "traefik.http.routers.vpn-radarr.rule=Host(`radarr.panda.tsphotoclicks.net`)"
      - "traefik.http.services.vpn-radarr.loadbalancer.server.port=7878"
      - "traefik.http.routers.vpn-radarr.middlewares=authentik@docker"
      # Sonarr related labels
      - "traefik.http.routers.vpn-sonarr.service=vpn-sonarr"
      - "traefik.http.routers.vpn-sonarr.entrypoints=websecure"
      - "traefik.http.routers.vpn-sonarr.tls.certresolver=myresolver"
      - "traefik.http.routers.vpn-sonarr.rule=Host(`sonarr.panda.tsphotoclicks.net`)"
      - "traefik.http.services.vpn-sonarr.loadbalancer.server.port=8989"
      - "traefik.http.routers.vpn-sonarr.middlewares=authentik@docker"
      # Whisparr related labels
      - "traefik.http.routers.vpn-whisparr.service=vpn-whisparr"
      - "traefik.http.routers.vpn-whisparr.entrypoints=websecure"
      - "traefik.http.routers.vpn-whisparr.tls.certresolver=myresolver"
      - "traefik.http.routers.vpn-whisparr.rule=Host(`whisparr.panda.tsphotoclicks.net`)"
      - "traefik.http.services.vpn-whisparr.loadbalancer.server.port=6969"
      # - "traefik.http.routers.vpn-whisparr.middlewares=authentik@docker"
    env_file:
      - ../.env/.env.default
      - ../.env/media/.env.gluetun
    ports:
      - "127.0.0.1:6767:6767" # bazarr
      - "127.0.0.1:8191:8191" # flaresolverr
      - "127.0.0.1:9696:9696" # prowlarr
      - "127.0.0.1:8085:8085" # qbittorrent
      - "127.0.0.1:7878:7878" # radarr
      - "127.0.0.1:8080:8080" # sabnzbd
      - "127.0.0.1:8989:8989" # sonarr
      - "127.0.0.1:6969:6969" # whisparr
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 60s
      timeout: 20s
      retries: 5

volumes:
  gluetun:
    external: true

networks:
  internal_ui:
    external: true