services: 
  jellyfin: 
    image: jellyfin/jellyfin:10.9.11
    container_name: jellyfin
    restart: always
    networks:
      - internal_ui
    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache
      - /TVShow:/tvshow
      - /Movie:/movie
    env_file:
      - ../.env/.env.default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.service=jellyfin"
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - "traefik.http.routers.jellyfin.tls.certresolver=myresolver"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.panda.tsphotoclicks.net`)"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
volumes:
  jellyfin_config:
    external: true
  jellyfin_cache:
    external: true
networks:
  internal_ui:
    external: true
    