services:
  prowlarr:
    image: linuxserver/prowlarr:1.26.1
    container_name: prowlarr
    restart: always
    network_mode: "service:gluetun"
    volumes:
      - prowlarr:/config
    depends_on:
      - gluetun
    env_file:
      - ../.env/.env.default
volumes:
  prowlarr:
    external: true