services:
  radarr:
    image: linuxserver/radarr:5.12.2
    container_name: radarr
    restart: always
    network_mode: "service:gluetun"
    volumes:
      - radarr:/config
      - /Movie:/movies
      - downloads:/downloads
    depends_on:
      - gluetun
    env_file:
      - ../.env/.env.default
volumes:
  radarr:
    external: true
  downloads:
    external: true