services:
  sabnzbd:
    image: linuxserver/sabnzbd:4.5.0
    container_name: sabnzbd
    restart: always
    network_mode: "service:gluetun"
    volumes:
      - sabnzbd:/config
      - downloads:/downloads
    depends_on:
      - gluetun
    env_file:
      - ../.env/.env.default
volumes:
  sabnzbd:
    external: true
  downloads:
    external: true