name: Docker Portainer Deploy On Beast

on:
  push:
    branches:
      - main
    paths:
      - 'beast/.env/network/**'
      - 'beast/network/**'
      - 'beast/network.yml'

jobs:
  deploy:
    runs-on: [self-hosted, beast]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update docker compose file for portainer
        run: |
          docker compose \
            --env-file "$HOME/.secrets/network.env" \
            -f $GITHUB_WORKSPACE/beast/network/portainer.yml \
            up -d