name: Docker Monitor Deploy On Beast

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'beast/.env/monitor/**'
      - 'beast/monitor/**'
      - 'beast/monitor.yml'

jobs:
  deploy:
    runs-on: [self-hosted, beast]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Update docker compose file for portainer
        run: |
          docker compose \
            --env-file "$HOME/.secrets/monitor.env" \
            -f $GITHUB_WORKSPACE/beast/monitor.yml \
            up -d