name: Docker Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: "self-hosted"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run curl command
        run: |
          curl -k -X POST "https://portainer.panda.tsphotoclicks.net/api/stacks/webhooks/40a2ed17-a709-4467-a23c-59ef4d353f9c"