name: Docker Media Deploy On Panda

on:
  push:
    branches:
      - main
    paths:
      - 'panda/.env/media/**'
      - 'panda/media/**'
      - 'panda/media.yml'

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run curl command
        run: |
          curl -k -X POST "https://portainer.panda.tsphotoclicks.net/api/stacks/webhooks/d64fcc0e-a28c-447b-b29e-97498195df5c"