name: Docker Network Deploy On Panda

on:
  push:
    branches:
      - main
    paths:
      - 'panda/.env/network/**'
      - 'panda/network/**'
      - 'panda/network.yml'
      - '!panda/network/portainer.yml'

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run curl command
        run: |
          curl -k -X POST "https://portainer.panda.tsphotoclicks.net/api/stacks/webhooks/325d6381-9340-4f9e-b0ef-dce4acdfe83d"