name: Docker Apps Deploy On Panda

on:
  push:
    branches:
      - main
    paths:
      - 'panda/access/**'

jobs:
  deploy:
    runs-on: "self-hosted"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run curl command
        run: |
          curl -k -X POST "https://portainer.panda.tsphotoclicks.net/api/stacks/webhooks/6f743025-b029-4168-b9c8-bf5b0c1b9379"