name: Docker Access Deploy On Panda

on:
  push:
    branches:
      - main
    paths:
      - 'panda/access/**'

jobs:
  deploy:
    runs-on: "self-hosted"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run curl command
        run: |
          curl -k -X POST "https://portainer.panda.tsphotoclicks.net/api/stacks/webhooks/8b579d88-a32d-4909-94db-a4935b7355d8"