name: Docker Network Deploy On Panda

on:
  push:
    branches:
      - main
    paths:
      - 'panda/network/**'
      - '!panda/network/portainer.yml'

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run curl command
        run: |
          curl -k -X POST "https://portainer.panda.tsphotoclicks.net/api/stacks/webhooks/e972ba44-4f32-4898-a97e-aa06e7f17d9e"